name: 'build'

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  Nuttx:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Build Nuttx
        uses: docker://docker.io/espressif/idf:v5.3
        with:
          args: /bin/sh -c "git config --global --add safe.directory '*' && ./esp32c3.sh"
