name: 'build'

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  Nuttx:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Build Nuttx
        uses: docker://docker.io/espressif/idf:v5.3
        with:
          args: /bin/sh -c "git config --global --add safe.directory '*' && ./esp32c3.sh"
      - uses: actions/upload-artifact@v4
        with:
          name: nuttx-builds
          path: out/

  Release-Artifacts:
    runs-on: ubuntu-20.04
    needs: [Nuttx]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: buildartifacts/
      - name: Update release
        if: "github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')"
        uses: pyTooling/Actions/releaser@r0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            buildartifacts/nuttx-builds/*
          tag: latest
          rm: true
